name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build and publish the Docker image to Github Packages
      env:
        tag: svejkciber/${{ github.event.repository.name }}:${{ github.sha }}
      run: |
        docker build . --file Dockerfile --tag ${tag}
        docker login -u ${{ secrets.DOCKERHUB_USER }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
        docker push ${tag}
